### ISSUE TITLE
Add support for SAM cli templates

### ISSUE THREAD

**Issue by tim-white87** [aws-scripting-guy/cform-VSCode#45]
Hey all, 
Great plugin, really enjoy it. When I use SAM cli templates like: 
``` 
DerpApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowHeaders: "'Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization'"
        AllowOrigin: "'*'" # TODO dynamic
        AllowMethods: "'POST, GET, OPTIONS'"
```
the plugin throws errors since the resource is an "invalid" value. Here are the docs around it: 
https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md
