### ISSUE TITLE
CloudFormation specific constructs are shown as invalid. 

### ISSUE THREAD

**Issue by msplival** [aws-scripting-guy/cform-VSCode#56]
Here is excerpt from my CloudFormation template for some Aurora stack:

```
AuroraClusterKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub "KMS key for - ${DBName}"
      EnableKeyRotation: true
      KeyPolicy:
        Statement:
          - Sid: !Sub '${DBName} Aurora PG Cluster KMS key policy'
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - kms:*
            Resource: "*"
```
But, all of the `!Sub ` sections are marked as 'Unresolved Tag'. 

I am using v0.0.24, freshly installed into VSCode.

![image](https://github.com/user-attachments/assets/560f181d-6efa-4b4f-a61a-855a645928eb)

I suppose I am doing something wrong, but I can't determine what :)
